# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='author',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='static/images/default_course.png', upload_to='static/images/courses', verbose_name='Изобразжение'),
        ),
        migrations.AddField(
            model_name='courses',
            name='url',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
